<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$b_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$_product = $block->getProduct();
$select_brand = $_product->getResource()->getAttribute('select_brand')->getFrontend()->getValue($_product);
$select_id = $_product->getDataByKey('select_brand');
//echo $select_id;
//echo "<pre>"; print_r($_product->debug());die("dead");
if ($select_brand != "No"): ?>
<a href="<?php echo $b_url.'/?select_brand='.$select_id; ?>">show all form <?php echo $select_brand; ?></a>
<?php endif;  ?>