<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$current_category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$_product = $block->getProduct();
$brand_name = $_product->getResource()->getAttribute('select_brand')->getFrontend()->getValue($_product);
$brand_id = $_product->getDataByKey('select_brand');

if ($brand_name != "No"): ?>
<style>
.product-info-main .product-reviews-summary, .customer-review .product-reviews-summary
   {
       margin-top: 10px;
   }
</style>
<a href="<?php echo $current_category->getUrl().'?select_brand='.$brand_id; ?>">Show All <?php echo $brand_name; ?> Brand Products</a>
<?php endif; ?>